services:
  # Serviço Web Principal
  - type: web
    name: bingx-trading-bot
    runtime: python
    plan: standard
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m alembic upgrade head
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bingx-redis
          property: connectionString
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true

  # Worker de Escaneamento
  - type: worker
    name: bingx-scanner-worker
    runtime: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m scanner.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bingx-redis
          property: connectionString
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false

  # Worker de Análise
  - type: worker
    name: bingx-analysis-worker
    runtime: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m analysis.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bingx-redis
          property: connectionString

  # Cache Redis
  - type: redis
    name: bingx-redis
    plan: starter
    ipAllowList: []

databases:
  # Banco de Dados PostgreSQL
  - name: bingx-postgres
    plan: standard
    databaseName: bingx_trading
    user: bingx_user
    ipAllowList: []

  # Background Maintenance Worker
  - type: worker
    name: bingx-maintenance-worker
    runtime: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m utils.maintenance_worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: LOG_RETENTION_DAYS
        value: "30"