services:
  # Main Web Service
  - type: web
    name: bingx-trading-bot
    runtime: python
    port: 10000
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m api
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bingx-redis
          property: connectionString
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true

  # Scanner Worker - Enhanced Performance Version
  - type: worker
    name: bingx-scanner-worker
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m scanner.enhanced_worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bingx-redis
          property: connectionString
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_SECRET_KEY
        sync: false
      - key: USE_PARALLEL_SCANNER
        value: "true"
      - key: SCAN_INTERVAL
        value: "10"
      - key: MAX_ASSETS_TO_SCAN
        value: "1500"

  # Analysis Worker
  - type: worker
    name: bingx-analysis-worker
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m analysis.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bingx-redis
          property: connectionString

  # Maintenance Worker
  - type: worker
    name: bingx-maintenance-worker
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m utils.maintenance_worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: bingx-postgres
          property: connectionString
      - key: LOG_RETENTION_DAYS
        value: "30"

  # Redis Cache
  - type: redis
    name: bingx-redis
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: bingx-postgres
    databaseName: bingx_trading
    user: bingx_user
    ipAllowList: []